# Generated by Django 2.1.7 on 2019-04-10 18:45

from django.db import migrations, models
import simplemooc.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190408_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(blank=True, choices=[(simplemooc.core.enums.Status_Course('Pendente'), 'Pendente'), (simplemooc.core.enums.Status_Course('Aprovado'), 'Aprovado'), (simplemooc.core.enums.Status_Course('Cancelado'), 'Cancelado'), (simplemooc.core.enums.Status_Course('Inscrito'), 'Inscrito')], default='Pendente', max_length=2, verbose_name='Situação'),
        ),
    ]
