# Generated by Django 2.1.7 on 2019-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='CountAnswers',
            new_name='replies',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='CountViews',
            new_name='views',
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='slug-test', verbose_name='Atalho'),
            preserve_default=False,
        ),
    ]
