# Generated by Django 2.1.7 on 2019-04-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190414_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Discussão', 'verbose_name_plural': 'Discussões'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussoes', to='courses.Course', verbose_name='Curso'),
        ),
    ]
