# Generated by Django 2.1.7 on 2019-04-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190416_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='views',
        ),
    ]
