# Generated by Django 2.1.7 on 2019-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_thread_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='correct',
            field=models.BooleanField(blank=True, default=False, verbose_name='Correta?'),
        ),
    ]
